version: "3.7"
                                                                                                                                                                                                                                                                                                                    
# Services

services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9090:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root

# docker compose up -d                                                                                                                                                     