version: "3.7"
                                                                                                                                                                                                                                                                                                                    
# Services
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      # - REDIS_USER=admin
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL    
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
      
 


# docker compose up -d                                                                                                                                                     